AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/ArgumentAlignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 35

Metrics/BlockLength:
  Enabled: true
  Max: 30

Lint/DuplicateBranch:
  Enabled: false
